export const freeGridStyles = {
  display: "grid",
  gridTemplateColumns: "repeat(12, minmax(0, 1fr))",
  gridTemplateRows: "repeat(8, 64px)",
  gridAutoRows: "64px",
  gap: "8px",
  alignItems: "flex-start",
  justifyItems: "stretch",
} as const;
export const presets = [
  { id: "free-grid", label: "자유 그리드", group: "레이아웃", tag: "div" },
  { id: "button", label: "버튼", group: "입력 요소", tag: "button" },
  { id: "dropdown", label: "드롭다운", group: "입력 요소", tag: "select" },
  { id: "input", label: "텍스트 입력", group: "입력 요소", tag: "input" },
  { id: "heading", label: "제목", group: "콘텐츠", tag: "h2" },
  { id: "paragraph", label: "본문", group: "콘텐츠", tag: "p" },
  { id: "divider", label: "구분선", group: "레이아웃", tag: "hr" },
  { id: "card", label: "카드", group: "레이아웃", tag: "article" },
  { id: "frame", label: "프레임", group: "레이아웃", tag: "div" },
  { id: "row", label: "가로", group: "레이아웃", tag: "div" },
  { id: "grid", label: "그리드", group: "레이아웃", tag: "div" },
] as const;
export type PresetId = (typeof presets)[number]["id"];
export const fonts = [
  "Arial, sans-serif",
  "Georgia, serif",
  "Verdana, sans-serif",
  "Trebuchet MS, sans-serif",
  "Courier New, monospace",
  "system-ui, sans-serif",
];
export const styleFields = {
  fontFamily: {
    label: "글꼴 종류",
    group: "글꼴",
    type: "select",
    options: fonts,
  },
  fontSize: { label: "글자 크기", group: "글꼴", type: "px" },
  fontWeight: {
    label: "글자 굵기",
    group: "글꼴",
    type: "select",
    options: ["300", "400", "500", "600", "700", "800", "900"],
  },
  fontStyle: {
    label: "글자 스타일",
    group: "글꼴",
    type: "select",
    options: ["normal", "italic"],
  },
  lineHeight: { label: "줄 높이", group: "글꼴", type: "px" },
  letterSpacing: {
    label: "자간",
    group: "글꼴",
    type: "signed-px",
  },
  textAlign: {
    label: "텍스트 정렬",
    group: "글꼴",
    type: "select",
    options: ["left", "center", "right", "justify"],
  },
  textDecorationLine: {
    label: "텍스트 장식",
    group: "글꼴",
    type: "select",
    options: ["none", "underline", "line-through"],
  },
  color: { label: "글자색", group: "모양", type: "color" },
  backgroundColor: { label: "배경색", group: "모양", type: "color" },
  borderColor: { label: "테두리 색", group: "모양", type: "color" },
  borderWidth: { label: "테두리 두께", group: "모양", type: "px" },
  borderStyle: {
    label: "테두리 스타일",
    group: "모양",
    type: "select",
    options: ["none", "solid", "dashed", "dotted"],
  },
  borderRadius: { label: "모서리 반경", group: "모양", type: "px" },
  opacity: { label: "불투명도", group: "모양", type: "number" },
  width: { label: "너비", group: "크기와 여백", type: "px" },
  height: { label: "높이", group: "크기와 여백", type: "px" },
  padding: { label: "안쪽 여백", group: "크기와 여백", type: "px" },
  margin: { label: "바깥 여백", group: "크기와 여백", type: "px" },
  display: {
    label: "레이아웃",
    group: "자동 배치",
    type: "select",
    options: ["block", "flex", "inline-flex", "grid"],
  },
  flexDirection: {
    label: "방향",
    group: "자동 배치",
    type: "select",
    options: ["row", "column", "row-reverse", "column-reverse"],
  },
  justifyContent: {
    label: "공간 배분",
    group: "자동 배치",
    type: "select",
    options: [
      "flex-start",
      "center",
      "flex-end",
      "space-between",
      "space-around",
      "space-evenly",
    ],
  },
  alignItems: {
    label: "요소 정렬",
    group: "자동 배치",
    type: "select",
    options: ["stretch", "flex-start", "center", "flex-end"],
  },
  gap: { label: "간격", group: "자동 배치", type: "px" },
  justifyItems: {
    label: "셀 안 정렬",
    group: "자동 배치",
    type: "select",
    options: ["flex-start", "center", "flex-end", "stretch"],
  },
  flexWrap: {
    label: "줄바꿈",
    group: "자동 배치",
    type: "select",
    options: ["nowrap", "wrap"],
  },
  gridTemplateColumns: {
    label: "그리드 열",
    group: "자동 배치",
    type: "select",
    options: [
      "repeat(1, minmax(0, 1fr))",
      "repeat(2, minmax(0, 1fr))",
      "repeat(3, minmax(0, 1fr))",
      "repeat(4, minmax(0, 1fr))",
      "repeat(6, minmax(0, 1fr))",
      "repeat(8, minmax(0, 1fr))",
      "repeat(12, minmax(0, 1fr))",
    ],
  },
  gridTemplateRows: {
    label: "그리드 행 수",
    group: "자동 배치",
    type: "select",
    options: ["none", "repeat(4, 64px)", "repeat(8, 64px)", "repeat(12, 64px)"],
  },
  gridAutoRows: {
    label: "빈 칸 배치",
    group: "자동 배치",
    type: "select",
    options: ["auto", "64px"],
  },
  gridColumnStart: {
    label: "시작 열",
    group: "그리드 위치",
    type: "select",
    options: ["auto", ...Array.from({ length: 12 }, (_, i) => String(i + 1))],
  },
  gridRowStart: {
    label: "시작 행",
    group: "그리드 위치",
    type: "select",
    options: ["auto", ...Array.from({ length: 40 }, (_, i) => String(i + 1))],
  },
  gridColumnEnd: {
    label: "차지할 열 수",
    group: "그리드 위치",
    type: "select",
    options: ["auto", ...Array.from({ length: 12 }, (_, i) => `span ${i + 1}`)],
  },
  gridRowEnd: {
    label: "차지할 행 수",
    group: "그리드 위치",
    type: "select",
    options: ["auto", ...Array.from({ length: 12 }, (_, i) => `span ${i + 1}`)],
  },
  translate: { label: "위치", group: "위치", type: "translate" },
} as const;

// Display labels only; CSS values and saved operations remain unchanged.
export const optionLabels: Record<string, string> = {
  normal: "기본",
  italic: "기울임",
  left: "왼쪽",
  center: "가운데",
  right: "오른쪽",
  justify: "양쪽 정렬",
  none: "없음",
  underline: "밑줄",
  "line-through": "취소선",
  solid: "실선",
  dashed: "파선",
  dotted: "점선",
  block: "블록",
  flex: "자동 배치 (Flex)",
  "inline-flex": "인라인 자동 배치",
  grid: "그리드",
  row: "가로",
  column: "세로",
  "row-reverse": "가로 역순",
  "column-reverse": "세로 역순",
  "flex-start": "시작",
  "flex-end": "끝",
  "space-between": "요소 사이 균등",
  "space-around": "요소 주변 균등",
  "space-evenly": "모든 간격 균등",
  stretch: "늘리기",
  nowrap: "줄바꿈 안 함",
  wrap: "줄바꿈",
};

export const elementLabels: Record<string, string> = {
  "page-root": "페이지 최상위",
  brand: "브랜드",
  "shop-link": "쇼핑 링크",
  "hero-content": "메인 영역",
  eyebrow: "소개 문구",
  "hero-title": "메인 제목",
  "hero-description": "메인 설명",
  "hero-button": "메인 버튼",
  "shipping-note": "배송 안내",
  "hero-art": "메인 이미지",
  "collection-title": "컬렉션 제목",
  "collection-cards": "카드 목록",
  "card-notes": "노트 카드",
  "notes-title": "노트 제목",
  "notes-description": "노트 설명",
  "card-focus": "집중 카드",
  "focus-title": "집중 제목",
  "focus-description": "집중 설명",
  "card-pause": "휴식 카드",
  "pause-title": "휴식 제목",
  "pause-description": "휴식 설명",
  "draft-board": "편집 보드",
};
