export const presets = [
  { id: "button", label: "Button", group: "Controls", tag: "button" },
  { id: "dropdown", label: "Dropdown", group: "Controls", tag: "select" },
  { id: "input", label: "Text input", group: "Controls", tag: "input" },
  { id: "heading", label: "Heading", group: "Content", tag: "h2" },
  { id: "paragraph", label: "Paragraph", group: "Content", tag: "p" },
  { id: "divider", label: "Divider", group: "Layout", tag: "hr" },
  { id: "card", label: "Card", group: "Layout", tag: "article" },
  { id: "frame", label: "Frame", group: "Layout", tag: "div" },
  { id: "row", label: "Row", group: "Layout", tag: "div" },
  { id: "grid", label: "Grid", group: "Layout", tag: "div" },
] as const;
export type PresetId = (typeof presets)[number]["id"];
export const fonts = [
  "Arial, sans-serif",
  "Georgia, serif",
  "Verdana, sans-serif",
  "Trebuchet MS, sans-serif",
  "Courier New, monospace",
  "system-ui, sans-serif",
];
export const styleFields = {
  fontFamily: {
    label: "Font family",
    group: "Typography",
    type: "select",
    options: fonts,
  },
  fontSize: { label: "Font size", group: "Typography", type: "px" },
  fontWeight: {
    label: "Font weight",
    group: "Typography",
    type: "select",
    options: ["300", "400", "500", "600", "700", "800", "900"],
  },
  fontStyle: {
    label: "Font style",
    group: "Typography",
    type: "select",
    options: ["normal", "italic"],
  },
  lineHeight: { label: "Line height", group: "Typography", type: "px" },
  letterSpacing: {
    label: "Letter spacing",
    group: "Typography",
    type: "signed-px",
  },
  textAlign: {
    label: "Text alignment",
    group: "Typography",
    type: "select",
    options: ["left", "center", "right", "justify"],
  },
  textDecorationLine: {
    label: "Text decoration",
    group: "Typography",
    type: "select",
    options: ["none", "underline", "line-through"],
  },
  color: { label: "Text color", group: "Appearance", type: "color" },
  backgroundColor: { label: "Background", group: "Appearance", type: "color" },
  borderColor: { label: "Border color", group: "Appearance", type: "color" },
  borderWidth: { label: "Border width", group: "Appearance", type: "px" },
  borderStyle: {
    label: "Border style",
    group: "Appearance",
    type: "select",
    options: ["none", "solid", "dashed", "dotted"],
  },
  borderRadius: { label: "Corner radius", group: "Appearance", type: "px" },
  opacity: { label: "Opacity", group: "Appearance", type: "number" },
  width: { label: "Width", group: "Size & spacing", type: "px" },
  height: { label: "Height", group: "Size & spacing", type: "px" },
  padding: { label: "Padding", group: "Size & spacing", type: "px" },
  margin: { label: "Margin", group: "Size & spacing", type: "px" },
  display: {
    label: "Layout",
    group: "Auto layout",
    type: "select",
    options: ["block", "flex", "inline-flex", "grid"],
  },
  flexDirection: {
    label: "Direction",
    group: "Auto layout",
    type: "select",
    options: ["row", "column", "row-reverse", "column-reverse"],
  },
  justifyContent: {
    label: "Distribute",
    group: "Auto layout",
    type: "select",
    options: [
      "flex-start",
      "center",
      "flex-end",
      "space-between",
      "space-around",
      "space-evenly",
    ],
  },
  alignItems: {
    label: "Align items",
    group: "Auto layout",
    type: "select",
    options: ["stretch", "flex-start", "center", "flex-end"],
  },
  gap: { label: "Gap", group: "Auto layout", type: "px" },
  flexWrap: {
    label: "Wrap",
    group: "Auto layout",
    type: "select",
    options: ["nowrap", "wrap"],
  },
  gridTemplateColumns: {
    label: "Grid columns",
    group: "Auto layout",
    type: "select",
    options: [
      "repeat(1, minmax(0, 1fr))",
      "repeat(2, minmax(0, 1fr))",
      "repeat(3, minmax(0, 1fr))",
      "repeat(4, minmax(0, 1fr))",
    ],
  },
  translate: { label: "Position", group: "Position", type: "translate" },
} as const;
